version: '3.1'

services:
  mysql:
      image: mysql:8
      restart: always
      environment:
        MYSQL_DB_ROOT_USERNAME: root
        MYSQL_DB_ROOT_PASSWORD: docker
      ports:
        - 3307:3306
  